version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 135808940904.dkr.ecr.ap-southeast-2.amazonaws.com
      - REPOSITORY_URL=135808940904.dkr.ecr.ap-southeast-2.amazonaws.com/devops-shroomguard
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the docker image
      - docker build -t $REPOSITORY_URL:latest -t $REPOSITORY_URL:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build successful on `date`
      - echo Pushing the Docker image
      - docker push $REPOSITORY_URL:latest
      - docker push $REPOSITORY_URL:$IMAGE_TAG
      - echo Writing image definitions file
      - printf '[{"name":"containerized-shroomguard","imageUri":"%s"}]' $REPOSITORY_URL:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
